from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

from app.schemas.ats import AtsAnalysis
from app.schemas.growth import SkillRoadmap
from app.schemas.interview import InterviewPrep
from app.schemas.jd import JDAnalysis
from app.schemas.recruiter import RecruiterReview
from app.schemas.risks import ResumeRisks

StepState = Literal["pending", "running", "done", "failed", "skipped"]
OverallStatus = Literal[
    "started", "running", "awaiting_review", "done", "failed"
]
ChangeCategory = Literal["summary", "skills", "experience", "projects", "keywords"]
# Resume PDF template the user picked on /home. Mirrors `resume_render.TEMPLATE_IDS`.
ResumeTemplate = Literal["classic", "minimal", "modern"]


class JobInputRequest(BaseModel):
    url: str | None = None
    raw_jd: str | None = None
    # Optional caller-supplied hints. Used as fallbacks when the JD itself
    # doesn't mention them, and as overrides when it does (the user knows
    # the canonical role/company better than a scraped page).
    company_name: str | None = None
    role_title: str | None = None


class PipelineRequest(BaseModel):
    file_id: str
    job_input: JobInputRequest
    want_cover_letter: bool = False
    candidate_email_to_send: str | None = None
    # Resume PDF style chosen on /home. Defaults to "classic" for back-compat.
    template_id: ResumeTemplate = "classic"
    # Caller-generated pipeline id. The frontend mints it before navigating
    # to /pipeline/<id>, so the URL is stable across the round-trip and we
    # can use the same id as the LangSmith trace thread id. Optional for
    # back-compat — server falls back to uuid4 when omitted.
    pipeline_id: str | None = None


class AgentStatus(BaseModel):
    name: str
    state: StepState
    started_at: datetime | None = None
    ended_at: datetime | None = None
    message: str | None = None


class PipelineProgress(BaseModel):
    pipeline_id: str
    overall_status: OverallStatus
    current_step: str | None = None
    steps: list[AgentStatus] = Field(default_factory=list)
    error: str | None = None
    started_at: datetime | None = None
    updated_at: datetime | None = None
    # Timing anchors for the live elapsed clock: when the analysis phase
    # ended (review pause begins) and when the generation phase started, so
    # the UI can show analysis + generation time while excluding the pause.
    analysis_ended_at: datetime | None = None
    generation_started_at: datetime | None = None


# How a single rewrite option for a proposed change was produced.
#   original — the candidate's current wording (a "keep what I have" choice)
#   ai       — an alternative phrasing generated by the analyst
#   custom   — the user's own free-text wording (placeholder text until typed)
ChangeOptionKind = Literal["original", "ai", "custom"]


class ChangeOption(BaseModel):
    """One selectable rewrite for a `ProposedChange`.

    The review screen renders these as radio choices: the original wording,
    two AI-generated alternatives, and a "write my own" box. Exactly one
    option per change is chosen before the resume writer runs.
    """

    id: str
    label: str
    text: str = ""
    kind: ChangeOptionKind = "ai"


class ProposedChange(BaseModel):
    """A single user-reviewable tailoring edit proposed by the resume analyst.

    During the `awaiting_review` pause the user (a) decides whether to apply
    the change at all (`accepted`) and (b) picks which wording to use among
    `options` (`selected_option_id`), or types their own (`custom_text`).
    Only accepted changes are passed to the resume writer in the generation
    phase. `accepted` defaults to True so an un-toggled change is kept.

    `after` is retained for back-compat with pipeline docs written before the
    multi-option model — it mirrors the first AI option's text.
    """

    id: str
    category: ChangeCategory
    title: str
    detail: str
    before: str | None = None
    after: str | None = None
    options: list[ChangeOption] = Field(default_factory=list)
    selected_option_id: str | None = None
    custom_text: str | None = None
    # For `skills` changes the review screen renders individual, clickable
    # skill chips (e.g. "Python", "LangGraph") instead of full-text options.
    # `chips` is the AI-suggested pool; `selected_chips` is the user's picks.
    chips: list[str] = Field(default_factory=list)
    selected_chips: list[str] | None = None
    accepted: bool = True


class PipelineReview(BaseModel):
    """Payload for the review screen shown while a pipeline is paused."""

    pipeline_id: str
    proposed_changes: list[ProposedChange] = Field(default_factory=list)
    analyst_summary: str | None = None
    candidate_name: str | None = None
    role_title: str | None = None
    company_name: str | None = None
    original_ats: AtsAnalysis | None = None
    # Template currently selected for the tailored resume PDF. The review
    # screen lets the user (re)pick before generation; defaults to "classic".
    template_id: ResumeTemplate = "classic"


class EmailDraftPayload(BaseModel):
    subject: str
    body: str
    to: str
    gmail_url: str


class PipelineResult(BaseModel):
    pipeline_id: str
    candidate_name: str
    role_title: str
    company_name: str
    fit_summary: str | None = None
    jd_analysis: JDAnalysis
    analyst_report: dict[str, Any]
    resume_pdf_url: str
    # Resume is delivered as PDF only now. Optional so older pipeline docs that
    # still carry a `resume_docx_url` continue to deserialise.
    resume_docx_url: str | None = None
    # Template the PDF was rendered with. Optional for pre-feature docs.
    template_id: ResumeTemplate = "classic"
    cover_letter_pdf_url: str | None = None
    cover_letter_docx_url: str | None = None
    email_draft: EmailDraftPayload | None = None
    ats_score: dict[str, Any]
    # Richer LLM-produced ATS scorecards for before/after comparison in the
    # UI. Optional so old pipeline docs (pre-feature) still deserialise.
    original_ats: AtsAnalysis | None = None
    tailored_ats: AtsAnalysis | None = None
    completed_at: datetime
    # Total active processing time (analysis + generation compute, excluding the
    # human review pause), in seconds. Optional for pre-feature docs.
    duration_seconds: int | None = None
    # Plain-text bodies kept so the frontend can render diffs and previews
    # without re-parsing the generated PDF/DOCX. Optional to stay
    # backwards-compatible with pipelines completed before this field landed.
    original_resume_text: str | None = None
    resume_text: str | None = None
    # Signed URL for the *originally uploaded* resume (PDF/DOCX/TXT) and the
    # raw JD text — used by the end-of-pipeline preview panel.
    original_resume_url: str | None = None
    original_resume_filename: str | None = None
    original_resume_file_type: str | None = None
    jd_text: str | None = None
    # Pre-computed, cached on the pipeline doc during the generation phase so
    # the always-on Skills & Growth and Interview tabs render instantly with
    # the result instead of firing a second on-mount request. Optional: old
    # docs (or a pipeline whose pre-compute step was skipped) won't have them,
    # in which case the tabs fall back to on-demand generation.
    interview_prep: InterviewPrep | None = None
    skill_roadmap: SkillRoadmap | None = None
    # On-demand agents cached on the doc the first time the user generates them.
    # Surfaced here so a reopened pipeline renders them straight from the result
    # — no re-fetch, no re-running the agent (and no auth round-trip).
    recruiter_review: RecruiterReview | None = None
    resume_risks: ResumeRisks | None = None
